version: "3"

services:

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
